In [0]:
#this code 
import zipfile
from google.colab import drive
drive.mount('/content/drive/')


In [0]:
#zip_ref = zipfile.ZipFile("/content/drive/My Drive/hdfc/data.zip", 'r')
#zip_ref.extractall("/content/drive/My Drive/hdfc/")
#zip_ref.close()

In [0]:
import os
os.getcwd()
os.chdir('/content/drive/My Drive/hdfc/')

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
 

In [5]:
df_train=pd.read_csv("DataSet/Train.csv")
df_test=pd.read_csv("DataSet/Test.csv")

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (700,731,740,752,761,789,811,820,829,841,850) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
#remove those columns that have only Nan values
for i in range(3,2395):
    try:
        p=all(df_train['Col{}'.format(i)].isnull())
        if p :
            df_train=df_train.drop(['Col{}'.format(i)],axis=1)
    except KeyError:
        pass




In [0]:
#preprocessing 
#1.check dataset contains any null
#2.check categorical data
#3.need decimal scalling

df_train.isnull().any(axis=0)

In [0]:
for i in range(3,2398):
    try:
      #calculate sum of nan values of every columns and go ahead
        sum_Nan=df_train['Col{}'.format(i)].isnull().sum()
        #70% data nan then remove columns
        #
        x70=(17521*7)/10
        x50=(17521*5)/10
        #if Nan value found then if condition true
        if sum_Nan >=x70:
            df_train=df_train.drop(['Col{}'.format(i)],axis=1)
           #if columns have morethan 50% data nan value and less 70% then  direct fill with 0 
        elif  sum_Nan <x70 and sum_Nan>x50:
            df_train['Col{}'.format(i)]=df_train['Col{}'.format(i)].fillna(np.mean(0))

        elif sum_Nan<x50:
            #then fill mean values
            df_train['Col{}'.format(i)]=df_train['Col{}'.format(i)].fillna(np.mean(df_train['Col{}'.format(i)]))


    except KeyError:
        pass

In [0]:
#extract featrues and labels
labels=df_train['Col2'].values        
features=df_train.iloc[:,2:]

#now perform decimal scalling
from sklearn.preprocessing import StandardScaler   
sc=StandardScaler()

features=sc.fit_transform(features)



In [0]:
from sklearn.model_selection import train_test_split
features_train,features_test,labels_train,labels_test=train_test_split(features,labels,random_state=0,test_size=0.2)

In [11]:
from sklearn.linear_model import  LogisticRegression
lr=LogisticRegression()
lr.fit(features_train,labels_train)
pred_lr=lr.predict(features_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm_lr=confusion_matrix(pred_lr,labels_test)
print(cm_lr)
print("Accuracy of Logistic =",accuracy_score(labels_test,pred_lr))


/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[[3066  308]
 [  96   35]]
Accuracy of Logistic = 0.8847360912981455


In [12]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()
dt.fit(features_train,labels_train)
pred_dt=dt.predict(features_test)
cm_dt=confusion_matrix(pred_dt,labels_test)
print(cm_dt)
print("Accuracy of DecisionTree =",accuracy_score(labels_test,pred_dt))


[[2839  281]
 [ 323   62]]
Accuracy of DecisionTree = 0.8276747503566334


In [13]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB
gnb=GaussianNB()
bnb=BernoulliNB()
mnb=MultinomialNB()
gnb.fit(features_train,labels_train)
pred_gnb=gnb.predict(features_test)
cm_gnb=confusion_matrix(pred_gnb,labels_test)
print(cm_gnb)
print(accuracy_score(labels_test,pred_gnb))

[[1638   99]
 [1524  244]]
0.5369472182596291


In [14]:
bnb.fit(features_train,labels_train)
pred_bnb=bnb.predict(features_test)
cm_bnb=confusion_matrix(pred_bnb,labels_test)
print(cm_bnb)
print(accuracy_score(labels_test,pred_bnb))

[[1871  115]
 [1291  228]]
0.5988587731811698


In [15]:
#apply knn algo
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,p=2)
knn.fit(features_train,labels_train)
pred_knn=knn.predict(features_test)
cm_pred=confusion_matrix(pred_knn,labels_test)
print(cm_pred)
print(accuracy_score(labels_test,pred_knn))


[[3129  333]
 [  33   10]]
0.8955777460770328


In [16]:
from sklearn.svm import  SVC
from sklearn.ensemble import RandomForestClassifier
svc=SVC(kernel='rbf',degree=3)
svc.fit(features_train,labels_train)
pred_svc=svc.predict(features_test)
cm_pred=confusion_matrix(pred_svc,labels_test)
print(accuracy_score(labels_test,pred_svc))

/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9021398002853067


In [17]:
rf= RandomForestClassifier(n_estimators=20, random_state=0)  
rf.fit(features_train,labels_train)
pred_rf=rf.predict(features_test)
print(confusion_matrix(pred_rf,labels_test))
print(accuracy_score(pred_rf,labels_test))

[[3144  334]
 [  18    9]]
0.8995720399429387


In [0]:
#SVC perform better and  accuracy_score is 90%

In [0]:
#after applying all classification algo now the turn to make a prediction on test data
#remove those columns that have only Nan values
for i in range(3,2395):
    try:
        p=all(df_test['Col{}'.format(i)].isnull())
        if p :
            df_test=df_test.drop(['Col{}'.format(i)],axis=1)
    except KeyError:
        pass

In [0]:
for i in range(3,2398):
    try:
      #calculate sum of nan values of every columns and go ahead
        sum_Nan=df_test['Col{}'.format(i)].isnull().sum()
        #70% data nan then remove columns
        #
        x70=(17521*7)/10
        x50=(17521*5)/10
        #if Nan value found then if condition true
        if sum_Nan >=x70:
            df_test=df_test.drop(['Col{}'.format(i)],axis=1)
           #if columns have morethan 50% data nan value and less 70% then  direct fill with 0 
        elif  sum_Nan <x70 and sum_Nan>x50:
            df_test['Col{}'.format(i)]=df_test['Col{}'.format(i)].fillna(np.mean(0))

        elif sum_Nan<x50:
            #then fill mean values
            df_test['Col{}'.format(i)]=df_test['Col{}'.format(i)].fillna(np.mean(df_test['Col{}'.format(i)]))


    except KeyError:
        pass

In [0]:
features_test=df_test.iloc[:,1:]

In [22]:
features_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20442 entries, 0 to 20441
Columns: 2175 entries, Col3 to Col2397
dtypes: float64(630), int64(1545)
memory usage: 339.2 MB


In [0]:
#use the features_scalling object to perform scalling but the train column does not match to test column so perform sepereate scalling
from sklearn.preprocessing import StandardScaler
sc_test=StandardScaler()
features_test=sc_test.fit_transform(features_test)

In [0]:
prediction=svc.predict(features_test)